gazebo_ros_control:
  pid_gains:
    left_wheel_joint:
      p: 40.0
      i: 0.05
      d: 22.0
    right_wheel_joint:
      p: 40.0
      i: 0.05
      d: 22.0

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
